# Generated by Django 3.1.1 on 2021-07-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
