# Generated by Django 3.1.1 on 2021-07-15 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemanager', '0002_auto_20210715_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='moment',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
