# Generated by Django 3.1.1 on 2021-07-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemanager', '0003_auto_20210715_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='moment',
            new_name='due_date',
        ),
    ]
