# Generated by Django 3.1.1 on 2021-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemanager', '0004_auto_20210715_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
