# Generated by Django 3.1.1 on 2021-07-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemanager', '0005_invoice_invoice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
