# Generated by Django 3.1.1 on 2021-07-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemanager', '0006_invoice_purchase_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
